### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [lutzroeder/Digger#1]
Which license is your game under?

**Comment by VladMarius** [comment]
Hello, i would also like to know , really nice implementation.

**Comment by 1stBitcoin** [comment]
U2? Happy x-mas!!
I believe it is output of backengeniring app. Nice understandable code, btw

**Comment by lutzroeder** [comment]
Graphics and levels are ported from an old game that was available in East Germany. The authors of the original game are Alexander Lang, Stefan Dahlke and Martin Guth.

**Comment by Trilarion** [comment]
Hi,

It seems the original game has been available for Linux under the license GPL-2.0 as xdigger but this re-implementation could be licensed differently. Because nothing in the source here indicates a license, is it also GPL or is it more like "All rights reserved"?

**Comment by KristjanESPERANTO** [comment]
Because the graphics, sounds and levels are the same as in the original version, it has to be GPL-2.0. At least as I understand it.

So I did a PR: #5.

**Comment by Trilarion** [comment]
Artwork can have a different license than the programming code. I would not infer that it has to be GPL-2.0.

Lutz Roeder did not really state the license in the comment from 2017, so the question is still open, I'd say.

Looking over it, I have also difficulties locating the game source code.

**Comment by KristjanESPERANTO** [comment]
My PR was just closed without any comment :-(

**Comment by KristjanESPERANTO** [comment]
I wrote to Alexander Lang. Let's see if the email address is still correct and what his opinion is about this.
